/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_udesign_cashlens_CashLensUtils */

#ifndef _Included_com_udesign_cashlens_CashLensUtils
#define _Included_com_udesign_cashlens_CashLensUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_udesign_cashlens_CashLensUtils
 * Method:    initLibYUV
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_udesign_cashlens_CashLensUtils_initLibYUV
  (JNIEnv *, jclass);

/*
 * Class:     com_udesign_cashlens_CashLensUtils
 * Method:    nv21ToRGB565
 * Signature: ([B[BII)V
 */
JNIEXPORT void JNICALL Java_com_udesign_cashlens_CashLensUtils_nv21ToRGB565
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
